In [40]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression



In [41]:
credit = pd.read_excel("C:/Users/Dell/Documents/imarticus/default of credit card clients.xls",header = 1)

<h1>EDA</h1>

In [42]:
credit.head(10)

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   
5   6      50000    1          1         2   37      0      0      0      0   
6   7     500000    1          1         2   29      0      0      0      0   
7   8     100000    2          2         2   23      0     -1     -1      0   
8   9     140000    2          3         1   28      0      0      2      0   
9  10      20000    1          3         2   35     -2     -2     -2     -2   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   
5  ...      19394      19619      20024      2500      1815       657   
6  ...     542653     483003     473944     55000     40000     38000   
7  ...        221       -159        567       380       601         0   
8  ...      12211      11793       3719      3329         0       432   
9  ...          0      13007      13912         0         0         0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0                           1  
1      1000         0      2000                           1  
2      1000      1000      5000                           0  
3      1100      1069      1000                           0  
4      9000       689       679                           0  
5      1000      1000       800                           0  
6     20239     13750     13770                           0  
7       581      1687      1542                           0  
8      1000      1000      1000                           0  
9     13007      1122         0                           0  

[10 rows x 25 columns]

In [43]:
credit.isnull().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64

In [44]:
train_x = credit.iloc[:20]
train_x.shape

(20, 25)

In [45]:
test_x = credit.iloc[20:]
test_x.shape

(29980, 25)

In [46]:
x = credit.drop("default payment next month",axis=1)
y= credit["default payment next month"]

In [47]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size = 0.2,random_state=10)#separating train and test

In [48]:
train_x.shape

(24000, 24)

In [49]:
credit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  int64
 13  BILL_AMT2                   30000 non-null  int64
 14  BILL_A

In [53]:
credit.columns= ["ID","LIMIT_BAL","SEX","EDUCATION","MARRIAGE","AGE","PAY_0","PAY_2","PAY_3","PAY_4","PAY_5","PAY_6","BILL_AMT1","BILL_AMT2","BILL_AMT3"  
                 ,"BILL_AMT4","BILL_AMT5","BILL_AMT6","PAY_AMT1","PAY_AMT2","PAY_AMT3","PAY_AMT4","PAY_AMT5","PAY_AMT6","default_payment"]

In [54]:
credit.head(2)

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default_payment  
0         0         0         0                1  
1      1000         0      2000                1  

[2 rows x 25 columns]

<h2>model</h2>


In [55]:
model=LogisticRegression().fit(train_x,train_y)

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [56]:
model.score(train_x,train_y)

0.778375

In [57]:
model.coef_

array([[-2.64246881e-05, -3.87226989e-06, -2.01490227e-07,
        -2.21122308e-07, -2.20343681e-07, -2.79476723e-06,
         5.44663965e-07,  4.37012664e-07,  3.80894165e-07,
         3.44018288e-07,  3.11483703e-07,  2.88807973e-07,
        -9.70053895e-06,  6.47262325e-06,  1.12929828e-06,
         3.88897305e-06,  3.71478304e-07,  2.27397551e-06,
        -3.39986633e-05, -2.22697766e-05, -9.75132525e-06,
        -9.13580139e-06, -5.30674131e-06, -1.13568036e-06]])

In [58]:
predict_y=model.predict(test_x)

In [59]:
model.predict_proba(test_x)

array([[0.91451168, 0.08548832],
       [0.5437405 , 0.4562595 ],
       [0.97566322, 0.02433678],
       ...,
       [0.83305892, 0.16694108],
       [0.75373813, 0.24626187],
       [0.63086154, 0.36913846]])

In [62]:
from sklearn.tree import DecisionTreeClassifier

In [63]:
model = DecisionTreeClassifier()
model.fit(train_x,train_y)
predictions = model.predict(test_x)
predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [66]:
model.fit(train_x,train_y)

DecisionTreeClassifier()

In [69]:
model.score(test_x,test_y)

0.7191666666666666